import type { InfluencerProfile } from '../types';

export const MOCK_INFLUENCERS: InfluencerProfile[] = [
  {
    id: 'inf-001',
    name: 'Clara Beaumont',
    handle: '@clarabeaumont',
    platforms: ['instagram', 'tiktok'],
    type: 'micro',
    followers: 87000,
    engagementRate: 5.2,
    niche: 'eco-fashion',
    estimatedBudgetMin: 800,
    estimatedBudgetMax: 2000,
    score: { total: 91, reachEngagement: 88, thematicAffinity: 95, brandSafety: 92, contentQuality: 90, credibility: 85 },
  },
  {
    id: 'inf-002',
    name: 'Lea Durand',
    handle: '@leadurand.style',
    platforms: ['instagram', 'youtube'],
    type: 'micro',
    followers: 42000,
    engagementRate: 6.8,
    niche: 'sustainable fashion',
    estimatedBudgetMin: 500,
    estimatedBudgetMax: 1200,
    score: { total: 88, reachEngagement: 82, thematicAffinity: 96, brandSafety: 90, contentQuality: 88, credibility: 80 },
  },
  {
    id: 'inf-003',
    name: 'Thomas Mercier',
    handle: '@thomasmercier',
    platforms: ['instagram', 'tiktok', 'youtube'],
    type: 'macro',
    followers: 320000,
    engagementRate: 2.1,
    niche: 'premium lifestyle',
    estimatedBudgetMin: 5000,
    estimatedBudgetMax: 12000,
    score: { total: 82, reachEngagement: 90, thematicAffinity: 72, brandSafety: 85, contentQuality: 78, credibility: 75 },
  },
  {
    id: 'inf-004',
    name: 'Ines Moreau',
    handle: '@inesmoreau.beauty',
    platforms: ['instagram', 'tiktok'],
    type: 'macro',
    followers: 156000,
    engagementRate: 3.4,
    niche: 'natural beauty',
    estimatedBudgetMin: 3000,
    estimatedBudgetMax: 7000,
    score: { total: 79, reachEngagement: 84, thematicAffinity: 78, brandSafety: 75, contentQuality: 72, credibility: 70 },
  },
  {
    id: 'inf-005',
    name: 'Hugo Lefevre',
    handle: '@hugostyle',
    platforms: ['tiktok', 'youtube'],
    type: 'micro',
    followers: 95000,
    engagementRate: 4.7,
    niche: 'fashion humor',
    estimatedBudgetMin: 1000,
    estimatedBudgetMax: 2500,
    score: { total: 76, reachEngagement: 80, thematicAffinity: 68, brandSafety: 82, contentQuality: 75, credibility: 72 },
  },
  {
    id: 'inf-006',
    name: 'Camille Roux',
    handle: '@camilleroux.slow',
    platforms: ['instagram', 'linkedin'],
    type: 'macro',
    followers: 210000,
    engagementRate: 1.8,
    niche: 'slow fashion',
    estimatedBudgetMin: 4000,
    estimatedBudgetMax: 9000,
    score: { total: 68, reachEngagement: 65, thematicAffinity: 80, brandSafety: 60, contentQuality: 65, credibility: 62 },
  },
  {
    id: 'inf-007',
    name: 'Sarah Martin',
    handle: '@sarahmartin.eco',
    platforms: ['instagram', 'tiktok'],
    type: 'micro',
    followers: 38000,
    engagementRate: 5.9,
    niche: 'sustainable living',
    estimatedBudgetMin: 400,
    estimatedBudgetMax: 900,
    score: { total: 62, reachEngagement: 58, thematicAffinity: 72, brandSafety: 55, contentQuality: 60, credibility: 68 },
  },
];
